version: '2'
networks:
  mired2:
    ipam:
      config:
        - subnet: 192.28.0.0/16
          gateway: 192.28.0.1
services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo_DB2
    networks:
      mired2:
        ipv4_address: 192.28.0.13
    ports:
      - "27017:27017"
    expose:
      - 27017
  app-agenda:
    image: danielgb29/agenda-microservice:1
    container_name: agenda-microservice
    networks:
      mired2:
        ipv4_address: 192.28.0.14
    expose:
      - 80
    ports:
      - "80:8097"
    depends_on:
      - db