server:
  port: 8097
spring:
  application:
    name: agenda-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 192.28.0.13
      database: agenda_service
      port: 27017
